# Generated by Django 2.0.7 on 2019-12-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='tb_blog',
        ),
        migrations.AlterModelTable(
            name='blogtype',
            table='tb_blogtype',
        ),
    ]
